name: MyLibrary
options:
  minimumXcodeGenVersion: 2.38.0
configs:
  Debug: debug
  Release: release
targets:
  MyLibrary:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: MyLibrary
        excludes:
          - "Preview Content/**"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.harleyludwig.MyLibrary
        PRODUCT_NAME: MyLibrary
        SWIFT_VERSION: 5.0
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: My Library
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_NSCameraUsageDescription: Scan book barcodes to quickly add books to your library.
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        DEVELOPMENT_TEAM: ""
